theme = "tokyonight"

[editor]
bufferline = "always"
cursorline = true
line-number = "relative"
rulers = [120]
true-color = true
end-of-line-diagnostics = "warning"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.indent-guides]
character = "╎"
render = true

[keys.normal]
X = "select_line_above"

[keys.select]
X = "select_line_above"
