[language-server.volar]
command = "vue-language-server"
args = ["--stdio"]
config = { typescript = { tsdk = "node_modules/typescript/lib/" } }

[language-server.tailwind]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.vtsls]
command = "vtsls"
args = ["--stdio"]

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "nu"
auto-format = true

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt" }

[[language]]
name = "fish"
auto-format = true

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "css"
auto-format = true
language-servers = ["tailwind"]
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "scss"
auto-format = true
language-servers = ["tailwind"]
formatter = { command = "prettier", args = ["--parser", "scss"] }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }

[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }

[[language]]
name = "typescript"
auto-format = true
language-servers = ["vtsls"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "babel"] }

[[language]]
name = "php"
auto-format = true
formatter = { command = "sh", args = ["-c", "phpcbf --standard=PSR12; exit 0"] }
